// Code generated by protoc-gen-gogo.
// source: github.com/synrobo/proto/region/region.proto
// DO NOT EDIT!

package region

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import common "github.com/synrobo/proto/common"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Region_RegionDataKeyspace_RegionDataKeyspaceType int32

const (
	Region_RegionDataKeyspace_KAIROSDB Region_RegionDataKeyspace_RegionDataKeyspaceType = 0
)

var Region_RegionDataKeyspace_RegionDataKeyspaceType_name = map[int32]string{
	0: "KAIROSDB",
}
var Region_RegionDataKeyspace_RegionDataKeyspaceType_value = map[string]int32{
	"KAIROSDB": 0,
}

func (x Region_RegionDataKeyspace_RegionDataKeyspaceType) String() string {
	return proto.EnumName(Region_RegionDataKeyspace_RegionDataKeyspaceType_name, int32(x))
}
func (Region_RegionDataKeyspace_RegionDataKeyspaceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorRegion, []int{0, 1, 0}
}

//
// Get all regions
type Region struct {
	// slug / ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human readable name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// IP range for devices
	IpRange *common.IPRange `protobuf:"bytes,3,opt,name=ip_range,json=ipRange" json:"ip_range,omitempty"`
	// State
	State *Region_RegionState `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
	// Keyspaces
	DataKeyspace []*Region_RegionDataKeyspace `protobuf:"bytes,5,rep,name=data_keyspace,json=dataKeyspace" json:"data_keyspace,omitempty"`
	// Location
	Location *common.GeoLocation `protobuf:"bytes,6,opt,name=location" json:"location,omitempty"`
}

func (m *Region) Reset()                    { *m = Region{} }
func (m *Region) String() string            { return proto.CompactTextString(m) }
func (*Region) ProtoMessage()               {}
func (*Region) Descriptor() ([]byte, []int) { return fileDescriptorRegion, []int{0} }

func (m *Region) GetIpRange() *common.IPRange {
	if m != nil {
		return m.IpRange
	}
	return nil
}

func (m *Region) GetState() *Region_RegionState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Region) GetDataKeyspace() []*Region_RegionDataKeyspace {
	if m != nil {
		return m.DataKeyspace
	}
	return nil
}

func (m *Region) GetLocation() *common.GeoLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

type Region_RegionState struct {
	MetaKeyspaceCreated       bool `protobuf:"varint,1,opt,name=meta_keyspace_created,json=metaKeyspaceCreated,proto3" json:"meta_keyspace_created,omitempty"`
	ConsulBootstrapperCreated bool `protobuf:"varint,2,opt,name=consul_bootstrapper_created,json=consulBootstrapperCreated,proto3" json:"consul_bootstrapper_created,omitempty"`
}

func (m *Region_RegionState) Reset()                    { *m = Region_RegionState{} }
func (m *Region_RegionState) String() string            { return proto.CompactTextString(m) }
func (*Region_RegionState) ProtoMessage()               {}
func (*Region_RegionState) Descriptor() ([]byte, []int) { return fileDescriptorRegion, []int{0, 0} }

type Region_RegionDataKeyspace struct {
	Name        string                                           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Created     bool                                             `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Replication map[string]int32                                 `protobuf:"bytes,3,rep,name=replication" json:"replication,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Type        Region_RegionDataKeyspace_RegionDataKeyspaceType `protobuf:"varint,4,opt,name=type,proto3,enum=region.Region_RegionDataKeyspace_RegionDataKeyspaceType" json:"type,omitempty"`
}

func (m *Region_RegionDataKeyspace) Reset()         { *m = Region_RegionDataKeyspace{} }
func (m *Region_RegionDataKeyspace) String() string { return proto.CompactTextString(m) }
func (*Region_RegionDataKeyspace) ProtoMessage()    {}
func (*Region_RegionDataKeyspace) Descriptor() ([]byte, []int) {
	return fileDescriptorRegion, []int{0, 1}
}

func (m *Region_RegionDataKeyspace) GetReplication() map[string]int32 {
	if m != nil {
		return m.Replication
	}
	return nil
}

func init() {
	proto.RegisterType((*Region)(nil), "region.Region")
	proto.RegisterType((*Region_RegionState)(nil), "region.Region.RegionState")
	proto.RegisterType((*Region_RegionDataKeyspace)(nil), "region.Region.RegionDataKeyspace")
	proto.RegisterEnum("region.Region_RegionDataKeyspace_RegionDataKeyspaceType", Region_RegionDataKeyspace_RegionDataKeyspaceType_name, Region_RegionDataKeyspace_RegionDataKeyspaceType_value)
}
func (m *Region) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Region) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintRegion(data, i, uint64(len(m.Id)))
		i += copy(data[i:], m.Id)
	}
	if len(m.Name) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintRegion(data, i, uint64(len(m.Name)))
		i += copy(data[i:], m.Name)
	}
	if m.IpRange != nil {
		data[i] = 0x1a
		i++
		i = encodeVarintRegion(data, i, uint64(m.IpRange.Size()))
		n1, err := m.IpRange.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.State != nil {
		data[i] = 0x22
		i++
		i = encodeVarintRegion(data, i, uint64(m.State.Size()))
		n2, err := m.State.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if len(m.DataKeyspace) > 0 {
		for _, msg := range m.DataKeyspace {
			data[i] = 0x2a
			i++
			i = encodeVarintRegion(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Location != nil {
		data[i] = 0x32
		i++
		i = encodeVarintRegion(data, i, uint64(m.Location.Size()))
		n3, err := m.Location.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}

func (m *Region_RegionState) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Region_RegionState) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.MetaKeyspaceCreated {
		data[i] = 0x8
		i++
		if m.MetaKeyspaceCreated {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.ConsulBootstrapperCreated {
		data[i] = 0x10
		i++
		if m.ConsulBootstrapperCreated {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *Region_RegionDataKeyspace) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Region_RegionDataKeyspace) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintRegion(data, i, uint64(len(m.Name)))
		i += copy(data[i:], m.Name)
	}
	if m.Created {
		data[i] = 0x10
		i++
		if m.Created {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if len(m.Replication) > 0 {
		for k, _ := range m.Replication {
			data[i] = 0x1a
			i++
			v := m.Replication[k]
			mapSize := 1 + len(k) + sovRegion(uint64(len(k))) + 1 + sovRegion(uint64(v))
			i = encodeVarintRegion(data, i, uint64(mapSize))
			data[i] = 0xa
			i++
			i = encodeVarintRegion(data, i, uint64(len(k)))
			i += copy(data[i:], k)
			data[i] = 0x10
			i++
			i = encodeVarintRegion(data, i, uint64(v))
		}
	}
	if m.Type != 0 {
		data[i] = 0x20
		i++
		i = encodeVarintRegion(data, i, uint64(m.Type))
	}
	return i, nil
}

func encodeFixed64Region(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Region(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintRegion(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *Region) Size() (n int) {
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovRegion(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovRegion(uint64(l))
	}
	if m.IpRange != nil {
		l = m.IpRange.Size()
		n += 1 + l + sovRegion(uint64(l))
	}
	if m.State != nil {
		l = m.State.Size()
		n += 1 + l + sovRegion(uint64(l))
	}
	if len(m.DataKeyspace) > 0 {
		for _, e := range m.DataKeyspace {
			l = e.Size()
			n += 1 + l + sovRegion(uint64(l))
		}
	}
	if m.Location != nil {
		l = m.Location.Size()
		n += 1 + l + sovRegion(uint64(l))
	}
	return n
}

func (m *Region_RegionState) Size() (n int) {
	var l int
	_ = l
	if m.MetaKeyspaceCreated {
		n += 2
	}
	if m.ConsulBootstrapperCreated {
		n += 2
	}
	return n
}

func (m *Region_RegionDataKeyspace) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovRegion(uint64(l))
	}
	if m.Created {
		n += 2
	}
	if len(m.Replication) > 0 {
		for k, v := range m.Replication {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovRegion(uint64(len(k))) + 1 + sovRegion(uint64(v))
			n += mapEntrySize + 1 + sovRegion(uint64(mapEntrySize))
		}
	}
	if m.Type != 0 {
		n += 1 + sovRegion(uint64(m.Type))
	}
	return n
}

func sovRegion(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozRegion(x uint64) (n int) {
	return sovRegion(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Region) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Region: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Region: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpRange", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.IpRange == nil {
				m.IpRange = &common.IPRange{}
			}
			if err := m.IpRange.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.State == nil {
				m.State = &Region_RegionState{}
			}
			if err := m.State.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataKeyspace", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataKeyspace = append(m.DataKeyspace, &Region_RegionDataKeyspace{})
			if err := m.DataKeyspace[len(m.DataKeyspace)-1].Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Location == nil {
				m.Location = &common.GeoLocation{}
			}
			if err := m.Location.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRegion(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRegion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Region_RegionState) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegionState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegionState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetaKeyspaceCreated", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MetaKeyspaceCreated = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsulBootstrapperCreated", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ConsulBootstrapperCreated = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipRegion(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRegion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Region_RegionDataKeyspace) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegion
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegionDataKeyspace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegionDataKeyspace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Created = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replication", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRegion
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthRegion
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(data[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			var valuekey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				valuekey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var mapvalue int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				mapvalue |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if m.Replication == nil {
				m.Replication = make(map[string]int32)
			}
			m.Replication[mapkey] = mapvalue
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Type |= (Region_RegionDataKeyspace_RegionDataKeyspaceType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRegion(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRegion
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRegion(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRegion
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRegion
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthRegion
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowRegion
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipRegion(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthRegion = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRegion   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorRegion = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x26, 0x69, 0xd3, 0x95, 0xd7, 0x32, 0xaa, 0x37, 0x40, 0x21, 0x48, 0x68, 0xec, 0x80, 0x10,
	0x82, 0x16, 0x95, 0xcb, 0xc4, 0x61, 0x12, 0x65, 0x80, 0xa6, 0x4d, 0x02, 0x79, 0xbb, 0x57, 0x4e,
	0x6a, 0x42, 0x44, 0x1b, 0x5b, 0x8e, 0x8b, 0x94, 0x23, 0xff, 0x8e, 0x13, 0xe2, 0xc8, 0x11, 0xf1,
	0x4b, 0x70, 0x6c, 0x37, 0x32, 0xa3, 0x88, 0x1d, 0x2c, 0xbf, 0xf7, 0xf9, 0xfb, 0xde, 0xe7, 0xf7,
	0x6c, 0x78, 0x92, 0x17, 0xea, 0xe3, 0x3a, 0x1d, 0x67, 0x7c, 0x35, 0xa9, 0xea, 0x52, 0xf2, 0x94,
	0x4f, 0x84, 0xe4, 0x8a, 0x4f, 0x24, 0xcb, 0x0b, 0x5e, 0xba, 0x6d, 0x6c, 0x30, 0xec, 0xd9, 0x2c,
	0x79, 0xea, 0xa9, 0x72, 0x9e, 0x3b, 0x49, 0xba, 0xfe, 0x60, 0x32, 0xab, 0x6f, 0x22, 0x2b, 0x4b,
	0xfe, 0x6d, 0xa2, 0x91, 0x95, 0x36, 0xb1, 0x9b, 0x65, 0x1f, 0xfc, 0x88, 0xa0, 0x47, 0x8c, 0x0f,
	0xee, 0x42, 0x58, 0x2c, 0xe2, 0x60, 0x3f, 0x78, 0x74, 0x9d, 0xe8, 0x08, 0x11, 0xba, 0x25, 0x5d,
	0xb1, 0x38, 0x34, 0x88, 0x89, 0xf1, 0x31, 0xf4, 0x0b, 0x31, 0x97, 0xb4, 0xcc, 0x59, 0xdc, 0xd1,
	0xf8, 0x60, 0x7a, 0x73, 0xec, 0xea, 0x9d, 0xbc, 0x27, 0x0d, 0x4c, 0x76, 0x0a, 0x61, 0x02, 0x7c,
	0x06, 0x51, 0xa5, 0xa8, 0x62, 0x71, 0xd7, 0x10, 0x93, 0xb1, 0xeb, 0x8e, 0xf8, 0xdb, 0x79, 0xc3,
	0x20, 0x96, 0x88, 0x6f, 0xe0, 0xc6, 0x82, 0x2a, 0x3a, 0xff, 0xc4, 0xea, 0x4a, 0xd0, 0x8c, 0xc5,
	0xd1, 0x7e, 0x47, 0x2b, 0x1f, 0x6c, 0x55, 0x1e, 0x6b, 0xe6, 0xa9, 0x23, 0x92, 0xe1, 0xc2, 0xcb,
	0x70, 0x02, 0xfd, 0x25, 0xcf, 0xa8, 0xd2, 0xac, 0xb8, 0x67, 0xcc, 0xf7, 0x36, 0xb7, 0x7c, 0xcb,
	0xf8, 0x99, 0x3b, 0x22, 0x2d, 0x29, 0xf9, 0x12, 0xc0, 0xc0, 0xbb, 0x0f, 0x4e, 0xe1, 0xf6, 0x8a,
	0x79, 0x17, 0x99, 0x67, 0x92, 0x69, 0xdc, 0x4e, 0xa7, 0x4f, 0xf6, 0x9a, 0xc3, 0x8d, 0xdb, 0x2b,
	0x7b, 0x84, 0x47, 0x70, 0x2f, 0xe3, 0x65, 0xb5, 0x5e, 0xce, 0x53, 0xce, 0x55, 0xa5, 0x24, 0x15,
	0x82, 0xc9, 0x56, 0x19, 0x1a, 0xe5, 0x5d, 0x4b, 0x99, 0x79, 0x0c, 0xa7, 0x4f, 0xbe, 0x85, 0x80,
	0x7f, 0x77, 0xd6, 0xbe, 0x42, 0xe0, 0xbd, 0x42, 0x0c, 0x3b, 0x7f, 0x96, 0xdd, 0xa4, 0x78, 0x01,
	0x03, 0xc9, 0xc4, 0xb2, 0x70, 0xcd, 0x77, 0xcc, 0xfc, 0xa6, 0xff, 0x9d, 0x9f, 0x86, 0x5a, 0xd1,
	0xeb, 0x52, 0xc9, 0x9a, 0xf8, 0x65, 0xf0, 0x0c, 0xba, 0xaa, 0x16, 0xf6, 0x21, 0x77, 0xa7, 0x87,
	0x57, 0x29, 0x77, 0x19, 0xba, 0xd0, 0x7a, 0x62, 0xaa, 0x24, 0x47, 0x30, 0xba, 0x6c, 0x87, 0x23,
	0xe8, 0xe8, 0x59, 0xbb, 0x26, 0x9b, 0x10, 0x6f, 0x41, 0xf4, 0x99, 0x2e, 0xd7, 0xf6, 0xfb, 0x45,
	0xc4, 0x26, 0x2f, 0xc2, 0xc3, 0xe0, 0xe0, 0x21, 0xdc, 0xd9, 0x5e, 0x1f, 0x87, 0xd0, 0x3f, 0x7d,
	0x79, 0x42, 0xde, 0x9d, 0x1f, 0xcf, 0x46, 0xd7, 0x66, 0xc3, 0xaf, 0xbf, 0xee, 0x07, 0xdf, 0xf5,
	0xfa, 0xa9, 0x57, 0xda, 0x33, 0xff, 0xfd, 0xf9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xb5,
	0x54, 0x2a, 0x84, 0x03, 0x00, 0x00,
}
