// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/proto/region/region-service.proto
// DO NOT EDIT!

/*
Package region is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/proto/region/region-service.proto
	github.com/fuserobotics/proto/region/region.proto

It has these top-level messages:
	ListRegionsRequest
	ListRegionsResponse
	CreateRegionRequest
	CreateRegionResponse
	SaveRegionRequest
	SaveRegionResponse
	Region
*/
package region

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import identify "github.com/fuserobotics/proto/identify"
import common "github.com/fuserobotics/proto/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListRegionsRequest struct {
	Identify *identify.Identify `protobuf:"bytes,1,opt,name=identify" json:"identify,omitempty"`
}

func (m *ListRegionsRequest) Reset()                    { *m = ListRegionsRequest{} }
func (m *ListRegionsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRegionsRequest) ProtoMessage()               {}
func (*ListRegionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ListRegionsRequest) GetIdentify() *identify.Identify {
	if m != nil {
		return m.Identify
	}
	return nil
}

type ListRegionsResponse struct {
	Region []*Region `protobuf:"bytes,1,rep,name=region" json:"region,omitempty"`
}

func (m *ListRegionsResponse) Reset()                    { *m = ListRegionsResponse{} }
func (m *ListRegionsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListRegionsResponse) ProtoMessage()               {}
func (*ListRegionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListRegionsResponse) GetRegion() []*Region {
	if m != nil {
		return m.Region
	}
	return nil
}

type CreateRegionRequest struct {
	Region *Region `protobuf:"bytes,1,opt,name=region" json:"region,omitempty"`
}

func (m *CreateRegionRequest) Reset()                    { *m = CreateRegionRequest{} }
func (m *CreateRegionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRegionRequest) ProtoMessage()               {}
func (*CreateRegionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateRegionRequest) GetRegion() *Region {
	if m != nil {
		return m.Region
	}
	return nil
}

type CreateRegionResponse struct {
	CreatedRegion *Region `protobuf:"bytes,1,opt,name=created_region,json=createdRegion" json:"created_region,omitempty"`
}

func (m *CreateRegionResponse) Reset()                    { *m = CreateRegionResponse{} }
func (m *CreateRegionResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateRegionResponse) ProtoMessage()               {}
func (*CreateRegionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateRegionResponse) GetCreatedRegion() *Region {
	if m != nil {
		return m.CreatedRegion
	}
	return nil
}

type SaveRegionRequest struct {
	Identify *identify.Identify  `protobuf:"bytes,1,opt,name=identify" json:"identify,omitempty"`
	Id       string              `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Name     string              `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Location *common.GeoLocation `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
}

func (m *SaveRegionRequest) Reset()                    { *m = SaveRegionRequest{} }
func (m *SaveRegionRequest) String() string            { return proto.CompactTextString(m) }
func (*SaveRegionRequest) ProtoMessage()               {}
func (*SaveRegionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SaveRegionRequest) GetIdentify() *identify.Identify {
	if m != nil {
		return m.Identify
	}
	return nil
}

func (m *SaveRegionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SaveRegionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SaveRegionRequest) GetLocation() *common.GeoLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

type SaveRegionResponse struct {
	Changed bool `protobuf:"varint,1,opt,name=changed" json:"changed,omitempty"`
}

func (m *SaveRegionResponse) Reset()                    { *m = SaveRegionResponse{} }
func (m *SaveRegionResponse) String() string            { return proto.CompactTextString(m) }
func (*SaveRegionResponse) ProtoMessage()               {}
func (*SaveRegionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SaveRegionResponse) GetChanged() bool {
	if m != nil {
		return m.Changed
	}
	return false
}

func init() {
	proto.RegisterType((*ListRegionsRequest)(nil), "region.ListRegionsRequest")
	proto.RegisterType((*ListRegionsResponse)(nil), "region.ListRegionsResponse")
	proto.RegisterType((*CreateRegionRequest)(nil), "region.CreateRegionRequest")
	proto.RegisterType((*CreateRegionResponse)(nil), "region.CreateRegionResponse")
	proto.RegisterType((*SaveRegionRequest)(nil), "region.SaveRegionRequest")
	proto.RegisterType((*SaveRegionResponse)(nil), "region.SaveRegionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RegionService service

type RegionServiceClient interface {
	ListRegions(ctx context.Context, in *ListRegionsRequest, opts ...grpc.CallOption) (*ListRegionsResponse, error)
	CreateRegion(ctx context.Context, in *CreateRegionRequest, opts ...grpc.CallOption) (*CreateRegionResponse, error)
	SaveRegion(ctx context.Context, in *SaveRegionRequest, opts ...grpc.CallOption) (*SaveRegionResponse, error)
}

type regionServiceClient struct {
	cc *grpc.ClientConn
}

func NewRegionServiceClient(cc *grpc.ClientConn) RegionServiceClient {
	return &regionServiceClient{cc}
}

func (c *regionServiceClient) ListRegions(ctx context.Context, in *ListRegionsRequest, opts ...grpc.CallOption) (*ListRegionsResponse, error) {
	out := new(ListRegionsResponse)
	err := grpc.Invoke(ctx, "/region.RegionService/ListRegions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionServiceClient) CreateRegion(ctx context.Context, in *CreateRegionRequest, opts ...grpc.CallOption) (*CreateRegionResponse, error) {
	out := new(CreateRegionResponse)
	err := grpc.Invoke(ctx, "/region.RegionService/CreateRegion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regionServiceClient) SaveRegion(ctx context.Context, in *SaveRegionRequest, opts ...grpc.CallOption) (*SaveRegionResponse, error) {
	out := new(SaveRegionResponse)
	err := grpc.Invoke(ctx, "/region.RegionService/SaveRegion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RegionService service

type RegionServiceServer interface {
	ListRegions(context.Context, *ListRegionsRequest) (*ListRegionsResponse, error)
	CreateRegion(context.Context, *CreateRegionRequest) (*CreateRegionResponse, error)
	SaveRegion(context.Context, *SaveRegionRequest) (*SaveRegionResponse, error)
}

func RegisterRegionServiceServer(s *grpc.Server, srv RegionServiceServer) {
	s.RegisterService(&_RegionService_serviceDesc, srv)
}

func _RegionService_ListRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRegionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).ListRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/region.RegionService/ListRegions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).ListRegions(ctx, req.(*ListRegionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionService_CreateRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).CreateRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/region.RegionService/CreateRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).CreateRegion(ctx, req.(*CreateRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegionService_SaveRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionServiceServer).SaveRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/region.RegionService/SaveRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionServiceServer).SaveRegion(ctx, req.(*SaveRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "region.RegionService",
	HandlerType: (*RegionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRegions",
			Handler:    _RegionService_ListRegions_Handler,
		},
		{
			MethodName: "CreateRegion",
			Handler:    _RegionService_CreateRegion_Handler,
		},
		{
			MethodName: "SaveRegion",
			Handler:    _RegionService_SaveRegion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/fuserobotics/proto/region/region-service.proto",
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/proto/region/region-service.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x4e, 0xea, 0x40,
	0x14, 0x4e, 0x81, 0x70, 0xb9, 0x87, 0x0b, 0xc9, 0x3d, 0xb8, 0xa8, 0xd5, 0x05, 0xe9, 0xc2, 0xb0,
	0xb1, 0x8d, 0x18, 0x16, 0x2e, 0x5c, 0x61, 0x34, 0x24, 0xb8, 0x29, 0x0f, 0x60, 0x4a, 0x3b, 0xc0,
	0x24, 0xb6, 0x83, 0x9d, 0x81, 0xc4, 0x37, 0xf1, 0x0d, 0x7d, 0x0d, 0xc3, 0xcc, 0x69, 0x2d, 0xd2,
	0x10, 0x59, 0xcd, 0xcc, 0xf9, 0x7e, 0xe6, 0x9b, 0x73, 0x06, 0xee, 0x96, 0x5c, 0xad, 0x36, 0x73,
	0x2f, 0x12, 0x89, 0xbf, 0xd8, 0x48, 0x96, 0x89, 0xb9, 0x50, 0x3c, 0x92, 0xfe, 0x3a, 0x13, 0x4a,
	0xf8, 0x19, 0x5b, 0x72, 0x91, 0xd2, 0x72, 0x2d, 0x59, 0xb6, 0xe5, 0x11, 0xf3, 0x34, 0x86, 0x4d,
	0x53, 0x75, 0x46, 0xc7, 0x2d, 0x78, 0xcc, 0x52, 0xc5, 0x17, 0xef, 0xc5, 0xc6, 0xc8, 0x9d, 0x9b,
	0x13, 0x6e, 0xfe, 0x9d, 0x24, 0x12, 0x49, 0x22, 0x52, 0x5a, 0x8c, 0xc4, 0x7d, 0x00, 0x9c, 0x72,
	0xa9, 0x02, 0x6d, 0x23, 0x03, 0xf6, 0xb6, 0x61, 0x52, 0xa1, 0x07, 0xad, 0x3c, 0x8d, 0x6d, 0xf5,
	0xad, 0x41, 0x7b, 0x88, 0x5e, 0x11, 0x6f, 0x42, 0x9b, 0xa0, 0xe0, 0xb8, 0xf7, 0xd0, 0xdb, 0x73,
	0x91, 0x6b, 0x91, 0x4a, 0x86, 0x57, 0x40, 0x3d, 0xb0, 0xad, 0x7e, 0x7d, 0xd0, 0x1e, 0x76, 0x3d,
	0x8a, 0x6b, 0x88, 0x01, 0xa1, 0x3b, 0xf9, 0x38, 0x63, 0xa1, 0x62, 0x54, 0xa7, 0x14, 0x65, 0xb9,
	0x75, 0x44, 0xfe, 0x0c, 0x67, 0xfb, 0x72, 0xba, 0x7e, 0x04, 0xdd, 0x48, 0xd7, 0xe3, 0x97, 0xa3,
	0x3e, 0x1d, 0x62, 0x99, 0xa3, 0xfb, 0x61, 0xc1, 0xff, 0x59, 0xb8, 0xfd, 0x11, 0xe6, 0xc4, 0x96,
	0x60, 0x17, 0x6a, 0x3c, 0xb6, 0x6b, 0x7d, 0x6b, 0xf0, 0x37, 0xa8, 0xf1, 0x18, 0x11, 0x1a, 0x69,
	0x98, 0x30, 0xbb, 0xae, 0x2b, 0x7a, 0x8f, 0x3e, 0xb4, 0x5e, 0x45, 0x14, 0xaa, 0x5d, 0xb4, 0x86,
	0xf6, 0xec, 0x79, 0x34, 0x9d, 0x27, 0x26, 0xa6, 0x04, 0x05, 0x05, 0xc9, 0xf5, 0x00, 0xcb, 0xc9,
	0xe8, 0x9d, 0x36, 0xfc, 0x89, 0x56, 0x61, 0xba, 0x64, 0xb1, 0x4e, 0xd6, 0x0a, 0xf2, 0xe3, 0xf0,
	0xd3, 0x82, 0x8e, 0x21, 0xcf, 0xcc, 0xd7, 0xc4, 0x47, 0x68, 0x97, 0x26, 0x85, 0x4e, 0xde, 0x8a,
	0xc3, 0x4f, 0xe0, 0x5c, 0x54, 0x62, 0x74, 0xe7, 0x04, 0xfe, 0x95, 0x7b, 0x8e, 0x05, 0xb9, 0x62,
	0x90, 0xce, 0x65, 0x35, 0x48, 0x56, 0x63, 0x80, 0xef, 0x47, 0xe1, 0x79, 0xce, 0x3d, 0x18, 0x81,
	0xe3, 0x54, 0x41, 0xc6, 0x64, 0xde, 0xd4, 0xdf, 0xf9, 0xf6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xe9,
	0x6b, 0x70, 0xf9, 0xb0, 0x03, 0x00, 0x00,
}
