// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/proto/common/common.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/proto/common/common.proto

It has these top-level messages:
	IPRange
	IPAddress
	CertChain
	GeoLocation
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// IP address CIDR
type IPRange struct {
	// IP data
	Ip *IPAddress `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	// Prefix length: 0->32
	Plen uint32 `protobuf:"varint,2,opt,name=plen" json:"plen,omitempty"`
}

func (m *IPRange) Reset()                    { *m = IPRange{} }
func (m *IPRange) String() string            { return proto.CompactTextString(m) }
func (*IPRange) ProtoMessage()               {}
func (*IPRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IPRange) GetIp() *IPAddress {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *IPRange) GetPlen() uint32 {
	if m != nil {
		return m.Plen
	}
	return 0
}

type IPAddress struct {
	Address []uint32 `protobuf:"varint,1,rep,packed,name=address" json:"address,omitempty"`
}

func (m *IPAddress) Reset()                    { *m = IPAddress{} }
func (m *IPAddress) String() string            { return proto.CompactTextString(m) }
func (*IPAddress) ProtoMessage()               {}
func (*IPAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IPAddress) GetAddress() []uint32 {
	if m != nil {
		return m.Address
	}
	return nil
}

// Certificate chain
type CertChain struct {
	// Cert chain, idx 0 should be last cert.
	Cert       []string `protobuf:"bytes,1,rep,name=cert" json:"cert,omitempty"`
	ValidUntil int64    `protobuf:"varint,2,opt,name=valid_until,json=validUntil" json:"valid_until,omitempty"`
	Csr        string   `protobuf:"bytes,3,opt,name=csr" json:"csr,omitempty"`
	CsrWaiting bool     `protobuf:"varint,4,opt,name=csr_waiting,json=csrWaiting" json:"csr_waiting,omitempty"`
}

func (m *CertChain) Reset()                    { *m = CertChain{} }
func (m *CertChain) String() string            { return proto.CompactTextString(m) }
func (*CertChain) ProtoMessage()               {}
func (*CertChain) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CertChain) GetCert() []string {
	if m != nil {
		return m.Cert
	}
	return nil
}

func (m *CertChain) GetValidUntil() int64 {
	if m != nil {
		return m.ValidUntil
	}
	return 0
}

func (m *CertChain) GetCsr() string {
	if m != nil {
		return m.Csr
	}
	return ""
}

func (m *CertChain) GetCsrWaiting() bool {
	if m != nil {
		return m.CsrWaiting
	}
	return false
}

// Equivilent to Point in RethinkDB
type GeoLocation struct {
	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *GeoLocation) Reset()                    { *m = GeoLocation{} }
func (m *GeoLocation) String() string            { return proto.CompactTextString(m) }
func (*GeoLocation) ProtoMessage()               {}
func (*GeoLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GeoLocation) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GeoLocation) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func init() {
	proto.RegisterType((*IPRange)(nil), "common.IPRange")
	proto.RegisterType((*IPAddress)(nil), "common.IPAddress")
	proto.RegisterType((*CertChain)(nil), "common.CertChain")
	proto.RegisterType((*GeoLocation)(nil), "common.GeoLocation")
}

func init() { proto.RegisterFile("github.com/fuserobotics/proto/common/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x49, 0x3b, 0xb6, 0xf5, 0x8d, 0xc1, 0xcc, 0xa9, 0xc8, 0xc0, 0xda, 0x53, 0xbd, 0x6c,
	0xa8, 0x5f, 0x40, 0xdd, 0x61, 0x0c, 0x3c, 0x8c, 0x80, 0x78, 0x1c, 0x69, 0x1a, 0xbb, 0x07, 0x6d,
	0x5e, 0x49, 0x52, 0xfd, 0xfa, 0xd2, 0x74, 0xce, 0x53, 0x7e, 0xef, 0xf7, 0xff, 0x27, 0x21, 0x81,
	0xc7, 0x1a, 0xfd, 0xb9, 0x2f, 0x37, 0x8a, 0xda, 0xed, 0x57, 0xef, 0xb4, 0xa5, 0x92, 0x3c, 0x2a,
	0xb7, 0xed, 0x2c, 0x79, 0xda, 0x2a, 0x6a, 0x5b, 0x32, 0x97, 0x65, 0x13, 0x1c, 0x9f, 0x8e, 0x53,
	0xfe, 0x02, 0xb3, 0xc3, 0x51, 0x48, 0x53, 0x6b, 0x7e, 0x0f, 0x11, 0x76, 0x29, 0xcb, 0x58, 0xb1,
	0x78, 0xba, 0xd9, 0x5c, 0xda, 0x87, 0xe3, 0x6b, 0x55, 0x59, 0xed, 0x9c, 0x88, 0xb0, 0xe3, 0x1c,
	0x26, 0x5d, 0xa3, 0x4d, 0x1a, 0x65, 0xac, 0x58, 0x8a, 0xc0, 0xf9, 0x03, 0x24, 0xd7, 0x12, 0x5f,
	0xc3, 0x4c, 0x8e, 0x98, 0xb2, 0x2c, 0x2e, 0x96, 0x6f, 0xd1, 0x8a, 0x89, 0x3f, 0x95, 0x3b, 0x48,
	0x76, 0xda, 0xfa, 0xdd, 0x59, 0xa2, 0x19, 0xce, 0x52, 0xda, 0xfa, 0xd0, 0x4b, 0x44, 0x60, 0x7e,
	0x07, 0x8b, 0x6f, 0xd9, 0x60, 0x75, 0xea, 0x8d, 0xc7, 0x26, 0x5c, 0x13, 0x0b, 0x08, 0xea, 0x63,
	0x30, 0x7c, 0x05, 0xb1, 0x72, 0x36, 0x8d, 0x33, 0x56, 0x24, 0x62, 0xc0, 0x61, 0x8b, 0x72, 0xf6,
	0xf4, 0x23, 0xd1, 0xa3, 0xa9, 0xd3, 0x49, 0xc6, 0x8a, 0xb9, 0x00, 0xe5, 0xec, 0xe7, 0x68, 0xf2,
	0x3d, 0x2c, 0xf6, 0x9a, 0xde, 0x49, 0x49, 0x8f, 0x64, 0xf8, 0x2d, 0xcc, 0x1b, 0xe9, 0xd1, 0xf7,
	0x95, 0x0e, 0x6f, 0x65, 0xe2, 0x3a, 0xf3, 0x35, 0x24, 0x0d, 0x99, 0x7a, 0x0c, 0xa3, 0x10, 0xfe,
	0x8b, 0x72, 0x1a, 0x7e, 0xee, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x3a, 0x84, 0x61, 0x6e,
	0x01, 0x00, 0x00,
}
