// Code generated by protoc-gen-gogo.
// source: github.com/synrobo/proto/device/device.proto
// DO NOT EDIT!

/*
	Package device is a generated protocol buffer package.

	It is generated from these files:
		github.com/synrobo/proto/device/device.proto

	It has these top-level messages:
		Device
*/
package device

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.GoGoProtoPackageIsVersion1

// Device: a full-linux computer running consul, docker stack
type Device struct {
	Hostname        string                        `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Region          string                        `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	ConsulSettings  *Device_DeviceConsulSettings  `protobuf:"bytes,3,opt,name=consul_settings,json=consulSettings" json:"consul_settings,omitempty"`
	NetworkSettings *Device_DeviceNetworkSettings `protobuf:"bytes,4,opt,name=network_settings,json=networkSettings" json:"network_settings,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptorDevice, []int{0} }

func (m *Device) GetConsulSettings() *Device_DeviceConsulSettings {
	if m != nil {
		return m.ConsulSettings
	}
	return nil
}

func (m *Device) GetNetworkSettings() *Device_DeviceNetworkSettings {
	if m != nil {
		return m.NetworkSettings
	}
	return nil
}

type Device_DeviceConsulSettings struct {
	IsServer         bool `protobuf:"varint,1,opt,name=is_server,json=isServer,proto3" json:"is_server,omitempty"`
	PreventBootstrap bool `protobuf:"varint,2,opt,name=prevent_bootstrap,json=preventBootstrap,proto3" json:"prevent_bootstrap,omitempty"`
}

func (m *Device_DeviceConsulSettings) Reset()         { *m = Device_DeviceConsulSettings{} }
func (m *Device_DeviceConsulSettings) String() string { return proto.CompactTextString(m) }
func (*Device_DeviceConsulSettings) ProtoMessage()    {}
func (*Device_DeviceConsulSettings) Descriptor() ([]byte, []int) {
	return fileDescriptorDevice, []int{0, 0}
}

type Device_DeviceNetworkSettings struct {
	// ip x 4 = ip address
	Ip []int32 `protobuf:"varint,1,rep,name=ip" json:"ip,omitempty"`
}

func (m *Device_DeviceNetworkSettings) Reset()         { *m = Device_DeviceNetworkSettings{} }
func (m *Device_DeviceNetworkSettings) String() string { return proto.CompactTextString(m) }
func (*Device_DeviceNetworkSettings) ProtoMessage()    {}
func (*Device_DeviceNetworkSettings) Descriptor() ([]byte, []int) {
	return fileDescriptorDevice, []int{0, 1}
}

func init() {
	proto.RegisterType((*Device)(nil), "device.Device")
	proto.RegisterType((*Device_DeviceConsulSettings)(nil), "device.Device.DeviceConsulSettings")
	proto.RegisterType((*Device_DeviceNetworkSettings)(nil), "device.Device.DeviceNetworkSettings")
}
func (m *Device) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Device) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Hostname) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Hostname)))
		i += copy(data[i:], m.Hostname)
	}
	if len(m.Region) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Region)))
		i += copy(data[i:], m.Region)
	}
	if m.ConsulSettings != nil {
		data[i] = 0x1a
		i++
		i = encodeVarintDevice(data, i, uint64(m.ConsulSettings.Size()))
		n1, err := m.ConsulSettings.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.NetworkSettings != nil {
		data[i] = 0x22
		i++
		i = encodeVarintDevice(data, i, uint64(m.NetworkSettings.Size()))
		n2, err := m.NetworkSettings.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}

func (m *Device_DeviceConsulSettings) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Device_DeviceConsulSettings) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.IsServer {
		data[i] = 0x8
		i++
		if m.IsServer {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.PreventBootstrap {
		data[i] = 0x10
		i++
		if m.PreventBootstrap {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *Device_DeviceNetworkSettings) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Device_DeviceNetworkSettings) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ip) > 0 {
		for _, num := range m.Ip {
			data[i] = 0x8
			i++
			i = encodeVarintDevice(data, i, uint64(num))
		}
	}
	return i, nil
}

func encodeFixed64Device(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Device(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintDevice(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *Device) Size() (n int) {
	var l int
	_ = l
	l = len(m.Hostname)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	l = len(m.Region)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	if m.ConsulSettings != nil {
		l = m.ConsulSettings.Size()
		n += 1 + l + sovDevice(uint64(l))
	}
	if m.NetworkSettings != nil {
		l = m.NetworkSettings.Size()
		n += 1 + l + sovDevice(uint64(l))
	}
	return n
}

func (m *Device_DeviceConsulSettings) Size() (n int) {
	var l int
	_ = l
	if m.IsServer {
		n += 2
	}
	if m.PreventBootstrap {
		n += 2
	}
	return n
}

func (m *Device_DeviceNetworkSettings) Size() (n int) {
	var l int
	_ = l
	if len(m.Ip) > 0 {
		for _, e := range m.Ip {
			n += 1 + sovDevice(uint64(e))
		}
	}
	return n
}

func sovDevice(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozDevice(x uint64) (n int) {
	return sovDevice(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Device) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Device: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Device: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hostname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hostname = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Region", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Region = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsulSettings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsulSettings == nil {
				m.ConsulSettings = &Device_DeviceConsulSettings{}
			}
			if err := m.ConsulSettings.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkSettings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NetworkSettings == nil {
				m.NetworkSettings = &Device_DeviceNetworkSettings{}
			}
			if err := m.NetworkSettings.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDevice(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Device_DeviceConsulSettings) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceConsulSettings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceConsulSettings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsServer", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsServer = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreventBootstrap", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PreventBootstrap = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipDevice(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Device_DeviceNetworkSettings) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceNetworkSettings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceNetworkSettings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Ip = append(m.Ip, v)
		default:
			iNdEx = preIndex
			skippy, err := skipDevice(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDevice(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthDevice
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowDevice
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipDevice(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthDevice = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDevice   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorDevice = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x50, 0xe1, 0x4a, 0xc3, 0x30,
	0x10, 0xa6, 0x9d, 0x96, 0xee, 0x94, 0x6d, 0x06, 0x95, 0x52, 0x41, 0x44, 0x05, 0x07, 0x6a, 0x0b,
	0xfa, 0x06, 0x73, 0x3f, 0x45, 0xa1, 0x7b, 0x80, 0xb9, 0xd6, 0x98, 0x05, 0x5d, 0xae, 0x24, 0x69,
	0xc5, 0x37, 0xf4, 0xa7, 0x8f, 0x20, 0xfe, 0xf0, 0x39, 0x8c, 0x69, 0x9c, 0x1b, 0xf4, 0x47, 0xb8,
	0xfb, 0xee, 0xbe, 0xef, 0xbb, 0xbb, 0xc0, 0x05, 0xe3, 0x7a, 0x5e, 0xe5, 0x49, 0x81, 0x8b, 0x54,
	0xbd, 0x09, 0x89, 0x39, 0xa6, 0xa5, 0x44, 0x8d, 0xe9, 0x23, 0xad, 0x79, 0x41, 0x5d, 0x48, 0x6c,
	0x8d, 0x04, 0x0d, 0x8a, 0x2f, 0x57, 0x54, 0x0c, 0x99, 0x93, 0xe4, 0xd5, 0x93, 0x45, 0x8d, 0xfe,
	0x37, 0x6b, 0x64, 0xc7, 0xdf, 0x3e, 0x04, 0x63, 0xab, 0x24, 0x31, 0x84, 0x73, 0x54, 0x5a, 0xcc,
	0x16, 0x34, 0xf2, 0x8e, 0xbc, 0x61, 0x37, 0x5b, 0x62, 0xb2, 0x0f, 0x81, 0xa4, 0x8c, 0xa3, 0x88,
	0x7c, 0xdb, 0x71, 0x88, 0xdc, 0x42, 0xbf, 0x40, 0xa1, 0xaa, 0x97, 0xa9, 0xa2, 0x5a, 0x73, 0xc1,
	0x54, 0xd4, 0x31, 0x84, 0xad, 0xab, 0x93, 0xc4, 0x6d, 0x37, 0x5e, 0x0d, 0x37, 0x96, 0x3b, 0x71,
	0xd4, 0xac, 0x57, 0xac, 0x61, 0x72, 0x0f, 0x03, 0x41, 0xf5, 0x2b, 0xca, 0xe7, 0x7f, 0xbb, 0x0d,
	0x6b, 0x77, 0xda, 0x6a, 0x77, 0xd7, 0x90, 0x97, 0x7e, 0x7d, 0xb1, 0x5e, 0x88, 0x1f, 0x60, 0xb7,
	0x6d, 0x30, 0x39, 0x80, 0x2e, 0x57, 0x66, 0x86, 0xac, 0xa9, 0xb4, 0xb7, 0x86, 0x59, 0xc8, 0xd5,
	0xc4, 0x62, 0x72, 0x0e, 0x3b, 0xa5, 0xa4, 0x35, 0x15, 0x7a, 0x9a, 0x23, 0x6a, 0xa5, 0xe5, 0xac,
	0xb4, 0x67, 0x87, 0xd9, 0xc0, 0x35, 0x46, 0x7f, 0xf5, 0xf8, 0x0c, 0xf6, 0x5a, 0x77, 0x21, 0x3d,
	0xf0, 0x79, 0x69, 0xbc, 0x3b, 0xc3, 0xcd, 0xcc, 0x64, 0xa3, 0xed, 0xf7, 0xaf, 0x43, 0xef, 0xc3,
	0xbc, 0x4f, 0xf3, 0xf2, 0xc0, 0xfe, 0xfe, 0xf5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x4b,
	0x7c, 0x95, 0xe4, 0x01, 0x00, 0x00,
}
