// Code generated by protoc-gen-gogo.
// source: github.com/synrobo/proto/device/device.proto
// DO NOT EDIT!

package device

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import common "github.com/synrobo/proto/common"
import metric "github.com/synrobo/proto/metric"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Device: a full-linux computer running consul, docker stack
type Device struct {
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Region   string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// Commited, unchangeable fqdn
	Fqdn            string                        `protobuf:"bytes,8,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	ConsulSettings  *Device_DeviceConsulSettings  `protobuf:"bytes,3,opt,name=consul_settings,json=consulSettings" json:"consul_settings,omitempty"`
	NetworkSettings *Device_DeviceNetworkSettings `protobuf:"bytes,4,opt,name=network_settings,json=networkSettings" json:"network_settings,omitempty"`
	SetupState      *Device_DeviceSetupState      `protobuf:"bytes,5,opt,name=setup_state,json=setupState" json:"setup_state,omitempty"`
	Identity        *Device_DeviceIdentity        `protobuf:"bytes,6,opt,name=identity" json:"identity,omitempty"`
	Metric          []*metric.MetricIdentifier    `protobuf:"bytes,7,rep,name=metric" json:"metric,omitempty"`
	CommitState     *common.CommitState           `protobuf:"bytes,9,opt,name=commit_state,json=commitState" json:"commit_state,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptorDevice, []int{0} }

func (m *Device) GetConsulSettings() *Device_DeviceConsulSettings {
	if m != nil {
		return m.ConsulSettings
	}
	return nil
}

func (m *Device) GetNetworkSettings() *Device_DeviceNetworkSettings {
	if m != nil {
		return m.NetworkSettings
	}
	return nil
}

func (m *Device) GetSetupState() *Device_DeviceSetupState {
	if m != nil {
		return m.SetupState
	}
	return nil
}

func (m *Device) GetIdentity() *Device_DeviceIdentity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Device) GetMetric() []*metric.MetricIdentifier {
	if m != nil {
		return m.Metric
	}
	return nil
}

func (m *Device) GetCommitState() *common.CommitState {
	if m != nil {
		return m.CommitState
	}
	return nil
}

type Device_DeviceConsulSettings struct {
	IsServer  bool `protobuf:"varint,1,opt,name=is_server,json=isServer,proto3" json:"is_server,omitempty"`
	Bootstrap bool `protobuf:"varint,2,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
}

func (m *Device_DeviceConsulSettings) Reset()         { *m = Device_DeviceConsulSettings{} }
func (m *Device_DeviceConsulSettings) String() string { return proto.CompactTextString(m) }
func (*Device_DeviceConsulSettings) ProtoMessage()    {}
func (*Device_DeviceConsulSettings) Descriptor() ([]byte, []int) {
	return fileDescriptorDevice, []int{0, 0}
}

type Device_DeviceNetworkSettings struct {
	Ip        *common.IPAddress               `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Interface []*Device_DeviceInterfaceConfig `protobuf:"bytes,2,rep,name=interface" json:"interface,omitempty"`
	Dns       []*common.IPAddress             `protobuf:"bytes,3,rep,name=dns" json:"dns,omitempty"`
}

func (m *Device_DeviceNetworkSettings) Reset()         { *m = Device_DeviceNetworkSettings{} }
func (m *Device_DeviceNetworkSettings) String() string { return proto.CompactTextString(m) }
func (*Device_DeviceNetworkSettings) ProtoMessage()    {}
func (*Device_DeviceNetworkSettings) Descriptor() ([]byte, []int) {
	return fileDescriptorDevice, []int{0, 1}
}

func (m *Device_DeviceNetworkSettings) GetIp() *common.IPAddress {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *Device_DeviceNetworkSettings) GetInterface() []*Device_DeviceInterfaceConfig {
	if m != nil {
		return m.Interface
	}
	return nil
}

func (m *Device_DeviceNetworkSettings) GetDns() []*common.IPAddress {
	if m != nil {
		return m.Dns
	}
	return nil
}

type Device_DeviceInterfaceConfig struct {
	Devname      string                                   `protobuf:"bytes,1,opt,name=devname,proto3" json:"devname,omitempty"`
	Ip           *common.IPAddress                        `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	GatewayIp    *common.IPAddress                        `protobuf:"bytes,3,opt,name=gateway_ip,json=gatewayIp" json:"gateway_ip,omitempty"`
	WifiSettings *Device_DeviceInterfaceConfig_WifiConfig `protobuf:"bytes,4,opt,name=wifi_settings,json=wifiSettings" json:"wifi_settings,omitempty"`
}

func (m *Device_DeviceInterfaceConfig) Reset()         { *m = Device_DeviceInterfaceConfig{} }
func (m *Device_DeviceInterfaceConfig) String() string { return proto.CompactTextString(m) }
func (*Device_DeviceInterfaceConfig) ProtoMessage()    {}
func (*Device_DeviceInterfaceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptorDevice, []int{0, 2}
}

func (m *Device_DeviceInterfaceConfig) GetIp() *common.IPAddress {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *Device_DeviceInterfaceConfig) GetGatewayIp() *common.IPAddress {
	if m != nil {
		return m.GatewayIp
	}
	return nil
}

func (m *Device_DeviceInterfaceConfig) GetWifiSettings() *Device_DeviceInterfaceConfig_WifiConfig {
	if m != nil {
		return m.WifiSettings
	}
	return nil
}

type Device_DeviceInterfaceConfig_WifiConfig struct {
	Network      []*Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork `protobuf:"bytes,1,rep,name=network" json:"network,omitempty"`
	ExtraOptions string                                                 `protobuf:"bytes,2,opt,name=extra_options,json=extraOptions,proto3" json:"extra_options,omitempty"`
}

func (m *Device_DeviceInterfaceConfig_WifiConfig) Reset() {
	*m = Device_DeviceInterfaceConfig_WifiConfig{}
}
func (m *Device_DeviceInterfaceConfig_WifiConfig) String() string { return proto.CompactTextString(m) }
func (*Device_DeviceInterfaceConfig_WifiConfig) ProtoMessage()    {}
func (*Device_DeviceInterfaceConfig_WifiConfig) Descriptor() ([]byte, []int) {
	return fileDescriptorDevice, []int{0, 2, 0}
}

func (m *Device_DeviceInterfaceConfig_WifiConfig) GetNetwork() []*Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork {
	if m != nil {
		return m.Network
	}
	return nil
}

type Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork struct {
	Ssid         string `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Proto        string `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	KeyMgmt      string `protobuf:"bytes,3,opt,name=key_mgmt,json=keyMgmt,proto3" json:"key_mgmt,omitempty"`
	Pairwise     string `protobuf:"bytes,4,opt,name=pairwise,proto3" json:"pairwise,omitempty"`
	Group        string `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Psk          string `protobuf:"bytes,6,opt,name=psk,proto3" json:"psk,omitempty"`
	ExtraOptions string `protobuf:"bytes,7,opt,name=extra_options,json=extraOptions,proto3" json:"extra_options,omitempty"`
}

func (m *Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork) Reset() {
	*m = Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork{}
}
func (m *Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork) String() string {
	return proto.CompactTextString(m)
}
func (*Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork) ProtoMessage() {}
func (*Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork) Descriptor() ([]byte, []int) {
	return fileDescriptorDevice, []int{0, 2, 0, 0}
}

type Device_DeviceSetupState struct {
	IdentityInited           bool `protobuf:"varint,1,opt,name=identity_inited,json=identityInited,proto3" json:"identity_inited,omitempty"`
	ConsulServerBootstrapped bool `protobuf:"varint,2,opt,name=consul_server_bootstrapped,json=consulServerBootstrapped,proto3" json:"consul_server_bootstrapped,omitempty"`
}

func (m *Device_DeviceSetupState) Reset()                    { *m = Device_DeviceSetupState{} }
func (m *Device_DeviceSetupState) String() string            { return proto.CompactTextString(m) }
func (*Device_DeviceSetupState) ProtoMessage()               {}
func (*Device_DeviceSetupState) Descriptor() ([]byte, []int) { return fileDescriptorDevice, []int{0, 3} }

type Device_DeviceIdentity struct {
	// Generated certs, latest is first
	Chain     []*common.CertChain `protobuf:"bytes,2,rep,name=chain" json:"chain,omitempty"`
	PublicKey string              `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (m *Device_DeviceIdentity) Reset()                    { *m = Device_DeviceIdentity{} }
func (m *Device_DeviceIdentity) String() string            { return proto.CompactTextString(m) }
func (*Device_DeviceIdentity) ProtoMessage()               {}
func (*Device_DeviceIdentity) Descriptor() ([]byte, []int) { return fileDescriptorDevice, []int{0, 4} }

func (m *Device_DeviceIdentity) GetChain() []*common.CertChain {
	if m != nil {
		return m.Chain
	}
	return nil
}

type DeviceNetworkTemplate struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *DeviceNetworkTemplate) Reset()                    { *m = DeviceNetworkTemplate{} }
func (m *DeviceNetworkTemplate) String() string            { return proto.CompactTextString(m) }
func (*DeviceNetworkTemplate) ProtoMessage()               {}
func (*DeviceNetworkTemplate) Descriptor() ([]byte, []int) { return fileDescriptorDevice, []int{1} }

func init() {
	proto.RegisterType((*Device)(nil), "device.Device")
	proto.RegisterType((*Device_DeviceConsulSettings)(nil), "device.Device.DeviceConsulSettings")
	proto.RegisterType((*Device_DeviceNetworkSettings)(nil), "device.Device.DeviceNetworkSettings")
	proto.RegisterType((*Device_DeviceInterfaceConfig)(nil), "device.Device.DeviceInterfaceConfig")
	proto.RegisterType((*Device_DeviceInterfaceConfig_WifiConfig)(nil), "device.Device.DeviceInterfaceConfig.WifiConfig")
	proto.RegisterType((*Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork)(nil), "device.Device.DeviceInterfaceConfig.WifiConfig.WifiNetwork")
	proto.RegisterType((*Device_DeviceSetupState)(nil), "device.Device.DeviceSetupState")
	proto.RegisterType((*Device_DeviceIdentity)(nil), "device.Device.DeviceIdentity")
	proto.RegisterType((*DeviceNetworkTemplate)(nil), "device.DeviceNetworkTemplate")
}
func (m *Device) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Device) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Hostname) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Hostname)))
		i += copy(data[i:], m.Hostname)
	}
	if len(m.Region) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Region)))
		i += copy(data[i:], m.Region)
	}
	if m.ConsulSettings != nil {
		data[i] = 0x1a
		i++
		i = encodeVarintDevice(data, i, uint64(m.ConsulSettings.Size()))
		n1, err := m.ConsulSettings.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.NetworkSettings != nil {
		data[i] = 0x22
		i++
		i = encodeVarintDevice(data, i, uint64(m.NetworkSettings.Size()))
		n2, err := m.NetworkSettings.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.SetupState != nil {
		data[i] = 0x2a
		i++
		i = encodeVarintDevice(data, i, uint64(m.SetupState.Size()))
		n3, err := m.SetupState.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.Identity != nil {
		data[i] = 0x32
		i++
		i = encodeVarintDevice(data, i, uint64(m.Identity.Size()))
		n4, err := m.Identity.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if len(m.Metric) > 0 {
		for _, msg := range m.Metric {
			data[i] = 0x3a
			i++
			i = encodeVarintDevice(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Fqdn) > 0 {
		data[i] = 0x42
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Fqdn)))
		i += copy(data[i:], m.Fqdn)
	}
	if m.CommitState != nil {
		data[i] = 0x4a
		i++
		i = encodeVarintDevice(data, i, uint64(m.CommitState.Size()))
		n5, err := m.CommitState.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	return i, nil
}

func (m *Device_DeviceConsulSettings) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Device_DeviceConsulSettings) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.IsServer {
		data[i] = 0x8
		i++
		if m.IsServer {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.Bootstrap {
		data[i] = 0x10
		i++
		if m.Bootstrap {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *Device_DeviceNetworkSettings) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Device_DeviceNetworkSettings) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Ip != nil {
		data[i] = 0xa
		i++
		i = encodeVarintDevice(data, i, uint64(m.Ip.Size()))
		n6, err := m.Ip.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if len(m.Interface) > 0 {
		for _, msg := range m.Interface {
			data[i] = 0x12
			i++
			i = encodeVarintDevice(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Dns) > 0 {
		for _, msg := range m.Dns {
			data[i] = 0x1a
			i++
			i = encodeVarintDevice(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *Device_DeviceInterfaceConfig) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Device_DeviceInterfaceConfig) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Devname) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Devname)))
		i += copy(data[i:], m.Devname)
	}
	if m.Ip != nil {
		data[i] = 0x12
		i++
		i = encodeVarintDevice(data, i, uint64(m.Ip.Size()))
		n7, err := m.Ip.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	if m.GatewayIp != nil {
		data[i] = 0x1a
		i++
		i = encodeVarintDevice(data, i, uint64(m.GatewayIp.Size()))
		n8, err := m.GatewayIp.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	if m.WifiSettings != nil {
		data[i] = 0x22
		i++
		i = encodeVarintDevice(data, i, uint64(m.WifiSettings.Size()))
		n9, err := m.WifiSettings.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n9
	}
	return i, nil
}

func (m *Device_DeviceInterfaceConfig_WifiConfig) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Device_DeviceInterfaceConfig_WifiConfig) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Network) > 0 {
		for _, msg := range m.Network {
			data[i] = 0xa
			i++
			i = encodeVarintDevice(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.ExtraOptions) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.ExtraOptions)))
		i += copy(data[i:], m.ExtraOptions)
	}
	return i, nil
}

func (m *Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ssid) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Ssid)))
		i += copy(data[i:], m.Ssid)
	}
	if len(m.Proto) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Proto)))
		i += copy(data[i:], m.Proto)
	}
	if len(m.KeyMgmt) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.KeyMgmt)))
		i += copy(data[i:], m.KeyMgmt)
	}
	if len(m.Pairwise) > 0 {
		data[i] = 0x22
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Pairwise)))
		i += copy(data[i:], m.Pairwise)
	}
	if len(m.Group) > 0 {
		data[i] = 0x2a
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Group)))
		i += copy(data[i:], m.Group)
	}
	if len(m.Psk) > 0 {
		data[i] = 0x32
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Psk)))
		i += copy(data[i:], m.Psk)
	}
	if len(m.ExtraOptions) > 0 {
		data[i] = 0x3a
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.ExtraOptions)))
		i += copy(data[i:], m.ExtraOptions)
	}
	return i, nil
}

func (m *Device_DeviceSetupState) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Device_DeviceSetupState) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.IdentityInited {
		data[i] = 0x8
		i++
		if m.IdentityInited {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.ConsulServerBootstrapped {
		data[i] = 0x10
		i++
		if m.ConsulServerBootstrapped {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *Device_DeviceIdentity) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Device_DeviceIdentity) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Chain) > 0 {
		for _, msg := range m.Chain {
			data[i] = 0x12
			i++
			i = encodeVarintDevice(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.PublicKey) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.PublicKey)))
		i += copy(data[i:], m.PublicKey)
	}
	return i, nil
}

func (m *DeviceNetworkTemplate) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *DeviceNetworkTemplate) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Id)))
		i += copy(data[i:], m.Id)
	}
	if len(m.Name) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Name)))
		i += copy(data[i:], m.Name)
	}
	if len(m.Description) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintDevice(data, i, uint64(len(m.Description)))
		i += copy(data[i:], m.Description)
	}
	return i, nil
}

func encodeFixed64Device(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Device(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintDevice(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *Device) Size() (n int) {
	var l int
	_ = l
	l = len(m.Hostname)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	l = len(m.Region)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	if m.ConsulSettings != nil {
		l = m.ConsulSettings.Size()
		n += 1 + l + sovDevice(uint64(l))
	}
	if m.NetworkSettings != nil {
		l = m.NetworkSettings.Size()
		n += 1 + l + sovDevice(uint64(l))
	}
	if m.SetupState != nil {
		l = m.SetupState.Size()
		n += 1 + l + sovDevice(uint64(l))
	}
	if m.Identity != nil {
		l = m.Identity.Size()
		n += 1 + l + sovDevice(uint64(l))
	}
	if len(m.Metric) > 0 {
		for _, e := range m.Metric {
			l = e.Size()
			n += 1 + l + sovDevice(uint64(l))
		}
	}
	l = len(m.Fqdn)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	if m.CommitState != nil {
		l = m.CommitState.Size()
		n += 1 + l + sovDevice(uint64(l))
	}
	return n
}

func (m *Device_DeviceConsulSettings) Size() (n int) {
	var l int
	_ = l
	if m.IsServer {
		n += 2
	}
	if m.Bootstrap {
		n += 2
	}
	return n
}

func (m *Device_DeviceNetworkSettings) Size() (n int) {
	var l int
	_ = l
	if m.Ip != nil {
		l = m.Ip.Size()
		n += 1 + l + sovDevice(uint64(l))
	}
	if len(m.Interface) > 0 {
		for _, e := range m.Interface {
			l = e.Size()
			n += 1 + l + sovDevice(uint64(l))
		}
	}
	if len(m.Dns) > 0 {
		for _, e := range m.Dns {
			l = e.Size()
			n += 1 + l + sovDevice(uint64(l))
		}
	}
	return n
}

func (m *Device_DeviceInterfaceConfig) Size() (n int) {
	var l int
	_ = l
	l = len(m.Devname)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	if m.Ip != nil {
		l = m.Ip.Size()
		n += 1 + l + sovDevice(uint64(l))
	}
	if m.GatewayIp != nil {
		l = m.GatewayIp.Size()
		n += 1 + l + sovDevice(uint64(l))
	}
	if m.WifiSettings != nil {
		l = m.WifiSettings.Size()
		n += 1 + l + sovDevice(uint64(l))
	}
	return n
}

func (m *Device_DeviceInterfaceConfig_WifiConfig) Size() (n int) {
	var l int
	_ = l
	if len(m.Network) > 0 {
		for _, e := range m.Network {
			l = e.Size()
			n += 1 + l + sovDevice(uint64(l))
		}
	}
	l = len(m.ExtraOptions)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	return n
}

func (m *Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork) Size() (n int) {
	var l int
	_ = l
	l = len(m.Ssid)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	l = len(m.Proto)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	l = len(m.KeyMgmt)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	l = len(m.Pairwise)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	l = len(m.Group)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	l = len(m.Psk)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	l = len(m.ExtraOptions)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	return n
}

func (m *Device_DeviceSetupState) Size() (n int) {
	var l int
	_ = l
	if m.IdentityInited {
		n += 2
	}
	if m.ConsulServerBootstrapped {
		n += 2
	}
	return n
}

func (m *Device_DeviceIdentity) Size() (n int) {
	var l int
	_ = l
	if len(m.Chain) > 0 {
		for _, e := range m.Chain {
			l = e.Size()
			n += 1 + l + sovDevice(uint64(l))
		}
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	return n
}

func (m *DeviceNetworkTemplate) Size() (n int) {
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovDevice(uint64(l))
	}
	return n
}

func sovDevice(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozDevice(x uint64) (n int) {
	return sovDevice(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Device) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Device: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Device: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hostname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hostname = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Region", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Region = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsulSettings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsulSettings == nil {
				m.ConsulSettings = &Device_DeviceConsulSettings{}
			}
			if err := m.ConsulSettings.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkSettings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NetworkSettings == nil {
				m.NetworkSettings = &Device_DeviceNetworkSettings{}
			}
			if err := m.NetworkSettings.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetupState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SetupState == nil {
				m.SetupState = &Device_DeviceSetupState{}
			}
			if err := m.SetupState.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Identity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Identity == nil {
				m.Identity = &Device_DeviceIdentity{}
			}
			if err := m.Identity.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metric", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metric = append(m.Metric, &metric.MetricIdentifier{})
			if err := m.Metric[len(m.Metric)-1].Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fqdn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fqdn = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CommitState == nil {
				m.CommitState = &common.CommitState{}
			}
			if err := m.CommitState.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDevice(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Device_DeviceConsulSettings) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceConsulSettings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceConsulSettings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsServer", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsServer = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bootstrap", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Bootstrap = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipDevice(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Device_DeviceNetworkSettings) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceNetworkSettings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceNetworkSettings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ip == nil {
				m.Ip = &common.IPAddress{}
			}
			if err := m.Ip.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Interface", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Interface = append(m.Interface, &Device_DeviceInterfaceConfig{})
			if err := m.Interface[len(m.Interface)-1].Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dns", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dns = append(m.Dns, &common.IPAddress{})
			if err := m.Dns[len(m.Dns)-1].Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDevice(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Device_DeviceInterfaceConfig) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceInterfaceConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceInterfaceConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Devname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Devname = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ip == nil {
				m.Ip = &common.IPAddress{}
			}
			if err := m.Ip.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GatewayIp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GatewayIp == nil {
				m.GatewayIp = &common.IPAddress{}
			}
			if err := m.GatewayIp.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WifiSettings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WifiSettings == nil {
				m.WifiSettings = &Device_DeviceInterfaceConfig_WifiConfig{}
			}
			if err := m.WifiSettings.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDevice(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Device_DeviceInterfaceConfig_WifiConfig) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WifiConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WifiConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Network", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Network = append(m.Network, &Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork{})
			if err := m.Network[len(m.Network)-1].Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraOptions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtraOptions = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDevice(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Device_DeviceInterfaceConfig_WifiConfig_WifiNetwork) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WifiNetwork: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WifiNetwork: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ssid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ssid = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proto", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proto = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyMgmt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyMgmt = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pairwise", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pairwise = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Group", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Group = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Psk", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Psk = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraOptions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtraOptions = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDevice(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Device_DeviceSetupState) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceSetupState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceSetupState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentityInited", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IdentityInited = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsulServerBootstrapped", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ConsulServerBootstrapped = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipDevice(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Device_DeviceIdentity) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceIdentity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceIdentity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = append(m.Chain, &common.CertChain{})
			if err := m.Chain[len(m.Chain)-1].Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDevice(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeviceNetworkTemplate) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceNetworkTemplate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceNetworkTemplate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDevice
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDevice(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthDevice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDevice(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDevice
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDevice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthDevice
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowDevice
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipDevice(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthDevice = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDevice   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorDevice = []byte{
	// 788 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x56, 0x92, 0x36, 0x1f, 0x93, 0x34, 0xed, 0xbb, 0x6f, 0xdf, 0x57, 0xc6, 0x50, 0x28, 0x2d,
	0x12, 0x1c, 0x20, 0xa9, 0x8a, 0x84, 0x84, 0xe0, 0x00, 0x4d, 0x2f, 0x11, 0x94, 0x82, 0x53, 0x04,
	0x17, 0x64, 0x25, 0xf6, 0xc6, 0x5d, 0xb5, 0xb1, 0x8d, 0x77, 0xd3, 0x90, 0xdf, 0x83, 0xf8, 0x15,
	0xdc, 0x11, 0x07, 0x0e, 0xfc, 0x04, 0xc4, 0x2f, 0x61, 0x76, 0xbc, 0x4e, 0xd2, 0x90, 0xf2, 0x71,
	0xb0, 0xbc, 0x33, 0xf3, 0xcc, 0xb3, 0xb3, 0xcf, 0xec, 0x2c, 0xdc, 0x0e, 0x84, 0x3a, 0x1e, 0xf6,
	0x1a, 0x5e, 0x34, 0x68, 0xca, 0x71, 0x98, 0x44, 0xbd, 0xa8, 0x19, 0x27, 0x91, 0x8a, 0x9a, 0x3e,
	0x3f, 0x13, 0x1e, 0x37, 0xbf, 0x06, 0xf9, 0x58, 0x31, 0xb5, 0xec, 0x3b, 0x33, 0x59, 0x41, 0x14,
	0x98, 0x94, 0xde, 0xb0, 0x4f, 0x56, 0x9a, 0xaf, 0x57, 0x69, 0x9a, 0x7d, 0xf1, 0x26, 0xe8, 0x19,
	0x44, 0xa1, 0xf9, 0xfd, 0x16, 0x3d, 0xe0, 0x2a, 0x11, 0x9e, 0xf9, 0xa5, 0xe8, 0xad, 0x2f, 0x55,
	0x28, 0xee, 0x53, 0x55, 0xcc, 0x86, 0xf2, 0x71, 0x24, 0x55, 0xd8, 0x1d, 0x70, 0x2b, 0xb7, 0x99,
	0xbb, 0x55, 0x71, 0x26, 0x36, 0xfb, 0x1f, 0x8a, 0x09, 0x0f, 0x44, 0x14, 0x5a, 0x79, 0x8a, 0x18,
	0x8b, 0x3d, 0x85, 0x55, 0x2f, 0x0a, 0xe5, 0xf0, 0xd4, 0x95, 0x5c, 0x29, 0x11, 0x06, 0xd2, 0x2a,
	0x20, 0xa0, 0xba, 0xbb, 0xdd, 0x30, 0x27, 0xdf, 0x9f, 0xfd, 0xb5, 0x08, 0xdb, 0x31, 0x50, 0xa7,
	0xee, 0x9d, 0xb3, 0xd9, 0x21, 0xac, 0x85, 0x5c, 0x8d, 0xa2, 0xe4, 0x64, 0x4a, 0xb7, 0x44, 0x74,
	0x37, 0x16, 0xd2, 0x3d, 0x4b, 0xc1, 0x13, 0xbe, 0xd5, 0xf0, 0xbc, 0x83, 0x3d, 0x82, 0x2a, 0x12,
	0x0d, 0x63, 0x57, 0xaa, 0xae, 0xe2, 0xd6, 0x32, 0x71, 0x5d, 0x5b, 0xc8, 0xd5, 0xd1, 0xb8, 0x8e,
	0x86, 0x39, 0x20, 0x27, 0x6b, 0x76, 0x1f, 0xca, 0xc2, 0xe7, 0xa1, 0x12, 0x6a, 0x6c, 0x15, 0x29,
	0x7d, 0x63, 0x61, 0x7a, 0xdb, 0x80, 0x9c, 0x09, 0x9c, 0xed, 0x40, 0x31, 0x95, 0xda, 0x2a, 0x6d,
	0x16, 0x30, 0xd1, 0x6a, 0x18, 0xe5, 0x0f, 0xe8, 0x97, 0x66, 0xf4, 0x05, 0x4f, 0x1c, 0x83, 0x63,
	0x0c, 0x96, 0xfa, 0x6f, 0xfd, 0xd0, 0x2a, 0x93, 0xc6, 0xb4, 0x66, 0xf7, 0xa0, 0xa6, 0xdb, 0x2b,
	0x94, 0x39, 0x43, 0x85, 0x8a, 0xf8, 0xb7, 0x61, 0x7a, 0xde, 0xa2, 0x58, 0x5a, 0x77, 0xd5, 0x9b,
	0x1a, 0xf6, 0x0b, 0x58, 0x5f, 0xa4, 0x39, 0xbb, 0x0c, 0x15, 0x21, 0x51, 0xde, 0xe4, 0x8c, 0x27,
	0xd4, 0xe6, 0x32, 0x96, 0x2c, 0x3b, 0x64, 0xb3, 0x2b, 0x50, 0xe9, 0x45, 0x91, 0x92, 0x2a, 0xe9,
	0xc6, 0xd4, 0xe9, 0xb2, 0x33, 0x75, 0xd8, 0xef, 0x73, 0xf0, 0xdf, 0x42, 0xe1, 0xd9, 0x75, 0xc8,
	0x8b, 0x98, 0xd8, 0xaa, 0xbb, 0xff, 0x64, 0xa5, 0xb5, 0x9f, 0x3f, 0xf6, 0xfd, 0x84, 0x4b, 0xe9,
	0x60, 0x90, 0xed, 0xe1, 0xbe, 0xa1, 0xe2, 0x49, 0xbf, 0xeb, 0x71, 0xa4, 0x2e, 0x5c, 0xd8, 0xd4,
	0x76, 0x86, 0xc2, 0xc2, 0xfb, 0x22, 0x70, 0xa6, 0x69, 0x6c, 0x1b, 0x0a, 0x7e, 0xa8, 0x6f, 0x58,
	0x61, 0xf1, 0x3e, 0x3a, 0x6a, 0x7f, 0x58, 0xca, 0xaa, 0x9c, 0x63, 0x62, 0x16, 0x94, 0x70, 0xc3,
	0x99, 0xfb, 0x9d, 0x99, 0xa6, 0xfe, 0xfc, 0xaf, 0xea, 0xdf, 0x01, 0x08, 0x50, 0xd7, 0x51, 0x77,
	0xec, 0x22, 0xb4, 0x70, 0x11, 0xb4, 0x62, 0x40, 0xed, 0x98, 0x1d, 0xc1, 0xca, 0x08, 0xfb, 0x3b,
	0x7f, 0x95, 0x9b, 0x7f, 0x72, 0xea, 0xc6, 0x2b, 0xcc, 0x34, 0x02, 0xd4, 0x34, 0x4b, 0x26, 0xb5,
	0xfd, 0x29, 0x0f, 0x30, 0x0d, 0xb2, 0x97, 0x50, 0x32, 0x97, 0x1e, 0xcf, 0xa4, 0x65, 0x79, 0xf0,
	0x97, 0xf4, 0xb4, 0x34, 0xfd, 0x74, 0x32, 0x2e, 0x54, 0x7a, 0x85, 0xbf, 0xc3, 0xa6, 0xbb, 0x51,
	0xac, 0x70, 0xce, 0xa5, 0x19, 0xfb, 0x1a, 0x39, 0x0f, 0x53, 0x9f, 0xfd, 0x31, 0x07, 0xd5, 0x99,
	0x6c, 0x7d, 0x7d, 0xa5, 0x14, 0xbe, 0x11, 0x97, 0xd6, 0x6c, 0x1d, 0x96, 0xe9, 0xa1, 0x31, 0x04,
	0xa9, 0xc1, 0x2e, 0x41, 0xf9, 0x84, 0x8f, 0xdd, 0x41, 0x30, 0x50, 0x24, 0x25, 0xb6, 0x02, 0xed,
	0x03, 0x34, 0xf5, 0x2b, 0x14, 0x77, 0x45, 0x32, 0x12, 0x92, 0x93, 0x60, 0xf8, 0x0a, 0x65, 0xb6,
	0x26, 0x0b, 0x92, 0x68, 0x18, 0xd3, 0x20, 0x23, 0x19, 0x19, 0x6c, 0x0d, 0x0a, 0xb1, 0x3c, 0xa1,
	0xe9, 0xac, 0x38, 0x7a, 0xf9, 0x73, 0xf5, 0xa5, 0x05, 0xd5, 0x8f, 0x61, 0x6d, 0x7e, 0xf2, 0xd9,
	0x4d, 0x58, 0xcd, 0xc6, 0xd7, 0x15, 0xa1, 0x50, 0xdc, 0x37, 0x23, 0x52, 0xcf, 0xdc, 0x6d, 0xf2,
	0xb2, 0x87, 0x60, 0x4f, 0xde, 0x3d, 0x3d, 0x39, 0xee, 0x64, 0x4a, 0x62, 0xcc, 0x49, 0x27, 0xc7,
	0xca, 0x5e, 0x37, 0x0d, 0xd8, 0x9b, 0x89, 0xdb, 0xaf, 0xa1, 0x7e, 0xfe, 0xd5, 0xc0, 0x8d, 0x97,
	0xbd, 0xe3, 0xae, 0x08, 0xcd, 0x64, 0x4c, 0x2e, 0x56, 0x8b, 0x27, 0xaa, 0xa5, 0x03, 0x4e, 0x1a,
	0x67, 0x1b, 0x00, 0xf1, 0xb0, 0x77, 0x2a, 0x3c, 0x17, 0x05, 0x33, 0xda, 0x55, 0x52, 0xcf, 0x13,
	0x3e, 0xde, 0x7a, 0x33, 0x37, 0xa1, 0x47, 0x7c, 0x10, 0x9f, 0xea, 0x93, 0xd5, 0xf1, 0x86, 0x67,
	0x9d, 0xc1, 0x95, 0xee, 0x15, 0x0d, 0x42, 0xda, 0x16, 0x5a, 0xb3, 0x4d, 0xa8, 0xfa, 0x5c, 0x7a,
	0x89, 0x20, 0x85, 0x0c, 0xf9, 0xac, 0x6b, 0xaf, 0xf6, 0xf9, 0xfb, 0xd5, 0xdc, 0x57, 0xfc, 0xbe,
	0xe1, 0xd7, 0x2b, 0x52, 0x33, 0xef, 0xfe, 0x08, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x61, 0xba, 0x31,
	0x05, 0x07, 0x00, 0x00,
}
